# Generated by Django 5.0.2 on 2024-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('numbers', models.IntegerField(default=0)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
