# Generated by Django 5.0.2 on 2024-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0004_message_delete_message2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='at_time',
            field=models.DateTimeField(),
        ),
    ]
