# Generated by Django 5.0.2 on 2024-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0004_country_number_delete_country2_delete_number2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('numbers', models.IntegerField(default=0)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('slug_id', models.CharField(default='oops', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Number2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('active_since', models.CharField(max_length=20)),
                ('sms', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('slug_id', models.CharField(default='oops', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
