# Generated by Django 5.0.2 on 2024-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0006_country_number_delete_country2_delete_number2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('at_time', models.CharField(max_length=20)),
                ('from_sndr', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='loaded_at',
        ),
    ]
